### ISSUE TITLE
not work with bindizip365

### ISSUE THREAD

**Issue by xmsec** [QiuChenly/MyMacsAppCrack#14]
bindizip365按照流程操作后无法正常解压文件，无法添加沙箱目录，可能是之前用过bindizip365，导致试用过期了。暂无法确定原因。

**Comment by QiuChenly** [comment]
可以解压 但是不能添加沙箱是因为app签名被修改了 暂时解决不了问题

**Comment by QiuChenly** [comment]
可以解压 但是不能添加沙箱是因为app签名被修改了 暂时解决不了问题
