### ISSUE TITLE
navicat我感觉操作步骤没问题，但是运行报错

### ISSUE THREAD

**Issue by nszy007** [QiuChenly/MyMacsAppCrack#17]
![1](https://user-images.githubusercontent.com/39269223/231635789-391f7d98-358c-46a9-9ff7-7f7cf9495634.jpg)
先是把库文件复制一个，然后添加注入，这里也没报错什么的。
然后运行的时候就提示找不到库文件了，这个是怎么回事呢？
![2](https://user-images.githubusercontent.com/39269223/231635940-826e3289-b8c4-4948-afc4-5df0abac739b.jpg)

**Comment by nszy007** [comment]
我自己搞错了，2个注入的库都要写绝对路径

**Comment by QiuChenly** [comment]
你的System Integrity Protection被打开了 由于Navicat没有做运行时固化 导致不需要关闭SIP也可以使用，这里建议到Recovery下关闭SIP以方便注入其他App
