### ISSUE TITLE
执行成功后无法打开

### ISSUE THREAD

**Issue by TommyChongg** [QiuChenly/MyMacsAppCrack#18]
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000152cb70 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

Crack的Bandizip

**Comment by QiuChenly** [comment]
1.附上错误截图
2.详细操作过程
3.不要太自信 一点有效的信息都没有 就说执行成功，根据我的经验有以下可能：
- SIP没关。
- 路径有空格，或者直接无脑复制shell就上去打开以为自己操作成功了。
- 无法打开后不知道什么叫做错误信息，随便复制了一段上来考验我。
4. 真正注入成功如果无法打开，则会提示:
- Dylib Load Failed
- 应用程序无法打开
- 注入文件注入完成之后随意删除，完全不考虑这个文件是否还需要。

请附上截图和操作详细步骤，如果无法提供任何有价值的信息可以关闭issues。
如果认为自己的操作没有问题，我看着自己电脑里的Bandizip 7.22对此表示Respect你的意见。

**Comment by TommyChongg** [comment]
感谢大神的回复，抱歉我可能说的不太详细。
1. 确实SIP没关，但是关了以后错误信息改变了：
  - 开启SIP：点开直接说无法打开（具体截图因为已经打开SIP就没有了），也没有显示detail的按钮，所以只能从terminal里面用open打开显示错误信息。
  - 关闭SIP后：点开的错误变成意外退出：
<img width="260" alt="image" src="https://user-images.githubusercontent.com/73205153/232302531-d5530249-238e-46ca-b6d8-5c3eb94a271c.png">
2. 以下是操作过程：
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/73205153/232302894-3fe1a0af-9494-48e3-9f7a-2ec193d8fc48.png">

**Comment by QiuChenly** [comment]
请点击Report...给出详细报错

**Comment by TommyChongg** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Bandizip365 [2481]
Path:                  /Applications/Bandizip365.app/Contents/MacOS/Bandizip365
Identifier:            com.bandisoft.mac.bandizip365
Version:               7.22 (220)
App Item ID:           1596426184
App External ID:       855911541
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-16 20:24:14.2378 +0800
OS Version:            macOS 13.3.1 (22E261)
Report Version:        12
Anonymous UUID:        6C7CC324-AC8E-1590-D2C0-5FA1A667FC37

Sleep/Wake UUID:       8E118123-45E1-4C9C-84C4-579CA937FF05

Time Awake Since Boot: 2200 seconds
Time Since Wake:       4 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Users/USER/Downloads/*/libInlineInjectPlugin.dylib
Referenced from: <FE8EFA65-93DC-328B-998B-1AB1B9E9A436> /Applications/Bandizip365.app/Contents/MacOS/Bandizip365
Reason: tried: '/Users/USER/Downloads/*/libInlineInjectPlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/USER/Downloads/*/libInlineInjectPlugin.dylib' (no such file), '/Users/USER/Downloads/*/libInlineInjectPlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libInlineInjectPlugin.dylib' (no such file), '/usr/lib/libInlineInjectPlugin.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                                 0x1a5799118 __abort_with_payload + 8
1   dyld                                 0x1a57a4d7c abort_with_payload_wrapper_internal + 104
2   dyld                                 0x1a57a4db0 abort_with_payload + 16
3   dyld                                 0x1a57308a8 dyld4::halt(char const*) + 328
4   dyld                                 0x1a572d590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                                 0x1a572be18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b78e9b0   x3: 0x0000000000000097
    x4: 0x000000016b78e5b0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000ba0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x00000001a572935c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b78e5b0  x21: 0x0000000000000097  x22: 0x000000016b78e9b0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000002013eacc0  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016b78e580   lr: 0x00000001a57a4d7c
    sp: 0x000000016b78e540   pc: 0x00000001a5799118 cpsr: 0x00001000
   far: 0x0000000104aec000  esr: 0x56000080  Address size fault

Binary Images:
       0x104670000 -        0x104a07fff com.bandisoft.mac.bandizip365 (7.22) <fe8efa65-93dc-328b-998b-1ab1b9e9a436> /Applications/Bandizip365.app/Contents/MacOS/Bandizip365
       0x1a5726000 -        0x1a57b453b dyld (*) <ac277a36-1808-327a-8761-cca585421212> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=804.7M resident=0K(0%) swapped_out_or_unallocated=804.7M(100%)
Writable regions: Total=8496K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8496K(100%)

                                VIRTUAL   REGION
REGION TYPE                        SIZE    COUNT (non-coalesced)
===========                     =======  =======
STACK GUARD                       56.0M        1
Stack                             8176K        1
VM_ALLOCATE                         16K        1
__DATA                             347K        3
__DATA_CONST                       134K        2
__DATA_DIRTY                         7K        1
__LINKEDIT                       800.6M        2
__TEXT                            4252K        2
dyld private memory                272K        2
===========                     =======  =======
TOTAL                            869.5M       15



-----------
Full Report
-----------

{"app_name":"Bandizip365","timestamp":"2023-04-16 20:24:14.00 +0800","app_version":"7.22","slice_uuid":"fe8efa65-93dc-328b-998b-1ab1b9e9a436","adam_id":"1596426184","build_version":"220","platform":1,"bundleID":"com.bandisoft.mac.bandizip365","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3.1 (22E261)","roots_installed":0,"name":"Bandizip365","incident_id":"3E30330A-2554-4F20-9BC6-8F5F95F07FCA"}
{
  "uptime" : 2200,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 1302,
  "osVersion" : {
    "train" : "macOS 13.3.1",
    "build" : "22E261",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-16 20:24:14.2378 +0800",
  "incident" : "3E30330A-2554-4F20-9BC6-8F5F95F07FCA",
  "pid" : 2481,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-16 20:24:14.2050 +0800",
  "procStartAbsTime" : 54289208377,
  "procExitAbsTime" : 54289874006,
  "procName" : "Bandizip365",
  "procPath" : "\/Applications\/Bandizip365.app\/Contents\/MacOS\/Bandizip365",
  "bundleInfo" : {"CFBundleShortVersionString":"7.22","CFBundleVersion":"220","CFBundleIdentifier":"com.bandisoft.mac.bandizip365"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1681641000000&sf=143480&pgtp=Search&pgid=osx&prpg=Search_osx&ctxt=Search&issrch=1&imptyp=card&kind=macSoftware&lngid=2","itemID":"1596426184","deviceIdentifierForVendor":"EF79AAC8-CD2D-5243-9758-CA7E55B49CDF","thirdParty":true,"softwareVersionExternalIdentifier":"855911541"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.bandisoft.mac.bandizip365",
  "crashReporterKey" : "6C7CC324-AC8E-1590-D2C0-5FA1A667FC37",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "",
  "codeSigningTeamID" : "",
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 4,
  "sleepWakeUUID" : "8E118123-45E1-4C9C-84C4-579CA937FF05",
  "sip" : "disabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/Users\/USER\/Downloads\/*\/libInlineInjectPlugin.dylib","Referenced from: <FE8EFA65-93DC-328B-998B-1AB1B9E9A436> \/Applications\/Bandizip365.app\/Contents\/MacOS\/Bandizip365","Reason: tried: '\/Users\/USER\/Downloads\/*\/libInlineInjectPlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/Users\/USER\/Downloads\/*\/libInlineInjectPlugin.dylib' (no such file), '\/Users\/USER\/Downloads\/*\/libInlineInjectPlugin.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '\/usr\/local\/lib\/libInlineInjectPlugin.dylib' (no such file), '\/usr\/lib\/libInlineInjectPlugin.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":43001,"threadState":{"x":[{"value":6},{"value":1},{"value":6098053552},{"value":151},{"value":6098052528},{"value":0},{"value":0},{"value":2976},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":50},{"value":4},{"value":32768},{"value":521},{"value":7070716764,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6098052528},{"value":151},{"value":6098053552},{"value":1},{"value":6},{"value":8610819264,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7071223164},"cpsr":{"value":4096},"fp":{"value":6098052480},"sp":{"value":6098052416},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7071174936,"matchesCrashFrame":1},"far":{"value":4373528576}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":1},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":1},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":1},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4368826368,
    "CFBundleShortVersionString" : "7.22",
    "CFBundleIdentifier" : "com.bandisoft.mac.bandizip365",
    "size" : 3768320,
    "uuid" : "fe8efa65-93dc-328b-998b-1ab1b9e9a436",
    "path" : "\/Applications\/Bandizip365.app\/Contents\/MacOS\/Bandizip365",
    "name" : "Bandizip365",
    "CFBundleVersion" : "220"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7070703616,
    "size" : 582972,
    "uuid" : "ac277a36-1808-327a-8761-cca585421212",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7070040064,
  "size" : 3539533824,
  "uuid" : "ebddd61c-5dcf-399c-a88b-759edf197103"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=804.7M resident=0K(0%) swapped_out_or_unallocated=804.7M(100%)\nWritable regions: Total=8496K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8496K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                             347K        3 \n__DATA_CONST                       134K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       800.6M        2 \n__TEXT                            4252K        2 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                            869.5M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "ce53d2dbecba5278e9bbf2fba4f4adc2a58b9621",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

Model: MacBookPro18,3, BootROM 8422.100.650, proc 8:6:2 processors, 16 GB, SMC
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Mar  8 2023 18:27:05 version 20.96.27.0.8.7.144 FWID 01-ec2ac09e
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.


On 16 Apr 2023, at 7:58 PM, 秋城落叶 ***@***.***> wrote:



请点击Report...给出详细报错

**Comment by TommyChongg** [comment]
看了下感觉是不是不支持M1？

**Comment by QiuChenly** [comment]
have 'x86_64', need 'arm64'  对的 你不是X86

**Comment by QiuChenly** [comment]
暂时不支持M1

**Comment by TommyChongg** [comment]
好吧😂感谢解答

On 16 Apr 2023, at 9:00 PM, 秋城落叶 ***@***.***> wrote:



暂时不支持M1

**Comment by QiuChenly** [comment]
但是可以打开Rosseta转译来尝试是否能正常使用 因为M1 会尝试模拟X86架构的内存映射

**Comment by TommyChongg** [comment]
有空试试，成功回来答复

On 16 Apr 2023, at 9:06 PM, 秋城落叶 ***@***.***> wrote:



但是可以打开Rosseta转译来尝试是否能正常使用 因为M1 会尝试模拟X86架构的内存映射

**Comment by nszy007** [comment]
https://www.52pojie.cn/thread-1732663-1-1.html
arm版可以参考作者的文章自己改，我已经测试成功了。
