### ISSUE TITLE
完全不知道怎么用

### ISSUE THREAD

**Issue by geekbb** [QiuChenly/MyMacsAppCrack#2]

**Comment by QiuChenly** [comment]
复制，执行指令，完成。

如 sudo insert_inject inlineInject.dylib 目标文件 目标文件
其中目标文件1 2 已经给出路径 文件带副本就是复制一份 使用说明在下面的Tips 如果你可以看到就会用了

**Comment by geekbb** [comment]
我用iShot Pro，知道对不对？
<img width="955" alt="image" src="https://user-images.githubusercontent.com/46196358/222862336-a95eac80-d46f-404b-9121-eb3ba6494741.png">

**Comment by geekbb** [comment]
还是？
<img width="908" alt="image" src="https://user-images.githubusercontent.com/46196358/222863265-7884a834-4cea-437b-a283-4a2ae24e82fc.png">

**Comment by QiuChenly** [comment]
实际上是insert_dylib的全路径 比如./insert_dylib 即可

**Comment by QiuChenly** [comment]
你应该执行他的可执行文件  他提示你inset_dylib未发现指令就是没加上可执行文件路径
sudo ~/downloads/tools/insert_dylib ~/downloads/tools/xxx.dylib 目标文件_副本 目标文件

**Comment by geekbb** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/46196358/222881285-b57a5ef4-0e1d-4edc-b228-7d178f87438c.png">
晚安，马卡巴卡

**Comment by geekbb** [comment]
删了吧，对不起，我放弃了😂

**Comment by QiuChenly** [comment]
chmod +x insert_dylib
这是因为文件虽然存在但是被系统识别成了未知文件 需要加上可执行文件权限

**Comment by hoochanlon** [comment]
> 删了吧，对不起，我放弃了😂

别呀；建议大佬你写个脚本小结一下，不过项目每个app的creak方法和路径也各有差异。有兴趣的话，看大佬你的需求慢慢完善咯，这里仅做个抛砖引玉。

```
chmod +x ~/Downloads/{insert_dylib,libInlineInjectPlugin.dylib}

read -p "把程序拖入到终端: " wait_creak_app

cp -p $wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster" \
$wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster的副本"

sudo ~/Downloads/{insert_dylib,libInlineInjectPlugin.dylib} \
$wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster的副本" \
$wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster"
```
如图示

<img width="941" alt="catch2023-03-13 23 54 49" src="https://user-images.githubusercontent.com/35732922/224756357-944bea10-79c2-4b3f-a3fa-7ef654fcb68e.png">

晚安，撒油啦啦。逃 ：）

**Comment by QiuChenly** [comment]
> > 删了吧，对不起，我放弃了😂
> 
> 别呀；建议大佬你写个脚本小结一下，不过项目每个app的creak方法和路径也各有差异。有兴趣的话，看大佬你的需求慢慢完善咯，这里仅做个抛砖引玉。
> 
> ```
> chmod +x ~/Downloads/{insert_dylib,libInlineInjectPlugin.dylib}
> 
> read -p "把程序拖入到终端: " wait_creak_app
> 
> cp -p $wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster" \
> $wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster的副本"
> 
> sudo ~/Downloads/{insert_dylib,libInlineInjectPlugin.dylib} \
> $wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster的副本" \
> $wait_creak_app"/Contents/Frameworks/XADMaster.framework/XADMaster"
> ```
> 
> 如图示
> 
> <img alt="catch2023-03-13 23 54 49" width="941" src="https://user-images.githubusercontent.com/35732922/224756357-944bea10-79c2-4b3f-a3fa-7ef654fcb68e.png">
> 
> 晚安，撒油啦啦。逃 ：）

谢谢，已经标记此解决方案，有时间将编写shell来进一步处理

**Comment by AjianYo** [comment]
但凡我上点心多翻翻closed里的issure...hhh，感谢这些提问者以及恢复者！！！
