### ISSUE TITLE
Adobe Lightroom Classic不行

### ISSUE THREAD

**Issue by flyingbird** [QiuChenly/MyMacsAppCrack#25]
Adobe Lightroom Classic破解只是假象，里面的“修改照片”功能是用不了的。

**Comment by QiuChenly** [comment]
其他app有问题吗

**Comment by QiuChenly** [comment]
已经在最新的提交中更正此问题。替换补丁文件后即时生效。
Commit Ref: 6c0f36b1803b475591bc0bfee499bdfd023797ca
