### ISSUE TITLE
请教关于frida的问题

### ISSUE THREAD

**Issue by nszy007** [QiuChenly/MyMacsAppCrack#26]
因最近入了个m2的mini所以学习下macos上的逆向，
我之前在windows上使用frida时直接frida -p pid就可以注入到进程了，但是在macos上时无论去注入任何进程始终提示报错，如下：
```
 410  访达                                                                                                     
(base) ➜  ~ sudo frida -p 410 
     ____
    / _  |   Frida 16.0.13 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Failed to attach: the connection is closed 
```
是macos需要特殊设置吗？
另：我学习作者的文章后成功通过修改二进制方式破解了bandizip365和超级右键，但是好像都因为签名原因导致权限问题使部分功能失效了。
作者有时间的时候方便分享一个简单完整的dylib修改源码吗，我想自己尝试学习修改一下arm版的这些软件。

**Comment by QiuChenly** [comment]
frida对部分app不起作用。原因是因为新版本的macOS作了API变更，有些app注入时机会过早或过迟，还有处理器的差异也会导致一部分的bug产生。dylib整理后会开源，敬请等待。

关于bandizip和超级右键的答复：
这两个app只能用内存注入的方式破解，类似于Paste，因为它们不存在可以被注入的第三方Framework，所以codesign后权限全部丢失且不存在开发者签名无法使用。

**Comment by nszy007** [comment]
非常感谢回复

秋城落叶 ***@***.***> 于2023年5月5日周五 23:34写道：
