### ISSUE TITLE
Failed to create ..../FluentUI

### ISSUE THREAD

**Issue by sqlmap3** [QiuChenly/MyMacsAppCrack#28]
Failed to create /Applications/Microsoft Excel.app/Contents/Frameworks/FluentUI.framework/Versions/A/FluentUI

**Comment by KangShanshuo** [comment]
Did you add "sudo" at the beginning of the command?

**Comment by QiuChenly** [comment]
Because u look's need sudo

**Comment by QiuChenly** [comment]
then cp the file

**Comment by QiuChenly** [comment]
sudo cp  /Applications/Microsoft Excel.app/Contents/Frameworks/FluentUI.framework/Versions/A/FluentUI  /Applications/Microsoft Excel.app/Contents/Frameworks/FluentUI.framework/Versions/A/FluentUI_副本

**Comment by QiuChenly** [comment]
can u understand what i mean?

**Comment by sqlmap3** [comment]
Just turn off SIP。

**Comment by QiuChenly** [comment]
Turn off SIP is required first

**Comment by QiuChenly** [comment]
It seems the problem has been resolved.
