### ISSUE TITLE
Crack 可以成功。但过一段时间就不行了，重新Crack还可以成功，但过一段时间还是运行不了。

### ISSUE THREAD

**Issue by newhuajun** [QiuChenly/MyMacsAppCrack#3]
试了这2个软件。
Omi NTFS 磁盘专家 Pro 1.2.3
Fig Player 1.2.2 
不知是不是我操作问题？
CleanMyMac 出了4.12.6正式版了。

**Comment by QiuChenly** [comment]
不要删除任何dylib文件。运行不了是因为你删掉了InlineInject.dylib或者移动了这个文件。他本质上是一个载体，而不是真的修改了目标二进制文件。

总结：把这个补丁文件放到一个不会移动的地方

**Comment by hoochanlon** [comment]
关于“InlineInject.dylib”、“insert_dylib” 的路径问题补档。要么自己手动，要么机器识别，以下以机器查找作为示例

```shell
# fd搜索工具，可装可不装，比自带的find快。前提得有homebrew
# brew install fd
# fd 查找的示例，-a 显示/返回绝对路径
# fd -a insert_dylib

chmod +x $(find $HOME -type f|grep "insert_dylib")
chmod +x $(find $HOME -type f|grep "libInlineInjectPlugin.dylib")

sudo $(find $HOME -type f|grep "insert_dylib") $(find $HOME -type f|grep "libInlineInjectPlugin.dylib") \
/Applications/OmniRecorder.app/Contents/MacOS/OmniRecorder_副本  \
/Applications/OmniRecorder.app/Contents/MacOS/OmniRecorder
```

**Comment by hoochanlon** [comment]
随缘更新，脚本测试

![catch2023-03-29 13 50 45](https://user-images.githubusercontent.com/35732922/228438845-9af86d56-6674-4302-818b-08b6d741bf2f.png)
