### ISSUE TITLE
报错 0x80000034

### ISSUE THREAD

**Issue by lugoing** [QiuChenly/MyMacsAppCrack#31]
➜  A sudo /Users/lugo/Downloads/MyMacsAppCrack-main/Tools/insert_dylib /Users/lugo/Downloads/MyMacsAppCrack-main/Tools/libInlineInjectPlugin.dylib /Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey_副本 /Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey
Password:
dyld: cannot load 'insert_dylib' (load command 0x80000034 is unknown)
[1]    1831 abort      sudo /Users/lugo/Downloads/MyMacsAppCrack-main/Tools/insert_dylib   

系统版本10.14.6 是不是系统老了？sip关了的。

**Comment by QiuChenly** [comment]
系统版本过低

**Comment by QiuChenly** [comment]
insert_dylib二进制编译的target sdk compatible 版本为10.15
