### ISSUE TITLE
大佬，ps都破解了，能安排一下开贝修图这个ps插件吗

### ISSUE THREAD

**Issue by crazyIceChen** [QiuChenly/MyMacsAppCrack#33]
详细阅读了大佬最新的 hotoShop CC 24.4.1: 基于LLDB动态调试与补丁注入 文章，太厉害了，修妹子不得快准狠来个插件吗 >_<

**Comment by QiuChenly** [comment]
下载地址在哪里

**Comment by crazyIceChen** [comment]
> 下载地址在哪里

这是是它官网的下载地址  https://pan.baidu.com/share/init?surl=7_vhiWCkxkR1UZgLaYCr6w&pwd=kbxz

**Comment by lockzzz** [comment]
win官方原版下载地址：
https://www.123pan.com/s/kiftVv-vH4a3.html

某宝低版本二次加密版
https://pan.baidu.com/s/10p45vTjmlXGxUR4o-nTFDw?pwd=b9iy

大佬有空看看能不能搞一搞，谢谢

**Comment by QiuChenly** [comment]
> 

这里是macOS软件，Windows软件不在讨论范围内。

**Comment by lockzzz** [comment]
明白，谢谢
&nbsp;


小风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月2日(星期五) 中午1:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QiuChenly/MyMacsAppCrack] 大佬，ps都破解了，能安排一下开贝修图这个ps插件吗 (Issue #33)





   
这里是macOS软件，Windows软件不在讨论范围内。
