### ISSUE TITLE
CleanMyMac 可以破解，但是运行时一直问password？

### ISSUE THREAD

**Issue by fastzhong** [QiuChenly/MyMacsAppCrack#34]
破解后试用版本的提示消失了，但是 Clean 时好像要装 helper，一直问 password，如何解决？

**Comment by QiuChenly** [comment]
阅读说明不仔细  已经写了不要codesign
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
你为什么要codesign  app谁教你的
