### ISSUE TITLE
希望可以支持PS v23.x.x.x版本

### ISSUE THREAD

**Issue by juning98** [QiuChenly/MyMacsAppCrack#40]
如题，穷鬼买不起m1/2的设备，机器上11以后的系统版本疯卡，所以只能使用10.15版本的系统，而10.15版本的系统只能支持到PSv23.x.x.x

**Comment by QiuChenly** [comment]
版本太老的不需要使用本补丁破解，可以寻找 Adobe Zii 之类的老工具。
