### ISSUE TITLE
Surge 5.1.1(2240)已经更新不了

### ISSUE THREAD

**Issue by GHA193** [QiuChenly/MyMacsAppCrack#44]
嗨大佬，进入试用版，点击更新，beta版本为5.1.1(2246)，注入之后Surge会崩溃，可是现在下不到2240版本了 QAQ
beta更新记录只能看到最新版的beta：https://www.nssurge.com/mac/v5/appcast-signed-beta.xml
秋叶大佬能否指教一下  谢谢
<img width="1185" alt="image" src="https://github.com/QiuChenly/MyMacsAppCrack/assets/24401268/57813300-92e1-4ac7-9030-81f8703682dc">

**Comment by GHA193** [comment]
找到了。需要检查beta版，打扰了

**Comment by QiuChenly** [comment]
崩溃的报告！

**Comment by GHA193** [comment]
> 崩溃的报告！

Sorry  忘记粘贴了
[Crash report.txt](https://github.com/QiuChenly/MyMacsAppCrack/files/11597112/Crash.report.txt)

**Comment by QiuChenly** [comment]
Library not loaded: /Volumes/VOLUME/*/libInlineInjectPlugin.dylib

不是 你非要把文件删了干什么？

**Comment by GHA193** [comment]
> 

哎呀 我也刚看到这个报错。。其实这个文件我放在另一个盘里面了，其实没有删除，可能是权限导致的，刚刚我放到home下了，确实也跟您说的这样，2246版本注入失效了

**Comment by QiuChenly** [comment]
已经修复.

**Comment by GHA193** [comment]
好嘞，多谢秋叶大佬！我试试去
