### ISSUE TITLE
苏州思杰马克丁也代理了Microsoft 365

### ISSUE THREAD

**Issue by hoochanlon** [QiuChenly/MyMacsAppCrack#5]
...

**Comment by iRubbish** [comment]
那是不是Office也将终结免费了😂

**Comment by hoochanlon** [comment]
> 那是不是Office也将终结免费了😂

从我发贴“涉及侵权”被驳回的猜测，感觉上，2021 for Mac应该是被他们盯上了。Windows上Office 2016/2019/2021，估计是不会的；微软这么聪明，肯定不会让思杰马克丁代理这玩意儿；不过，Office365本身就是订阅，给思杰马克丁反倒能规范化。
