### ISSUE TITLE
求软件工具

### ISSUE THREAD

**Issue by iRubbish** [QiuChenly/MyMacsAppCrack#6]
Hopper Disassembler 5.3.4 52没搜索到，可能我搜索姿势不对
顺带 贴一下 IDA 😂

求求求求

**Comment by QiuChenly** [comment]
在52论坛中macOS区有5.7.7下载地址
IDA也是 有人分享出来免安装包 仔细看帖

**Comment by iRubbish** [comment]
![image](https://user-images.githubusercontent.com/32736415/223299604-daf2aeb1-1134-4fe5-a910-fed17849ec61.png)
大佬真没看到😂，是不是咱们权限不同哈

**Comment by iRubbish** [comment]
> ![image](https://user-images.githubusercontent.com/32736415/223299604-daf2aeb1-1134-4fe5-a910-fed17849ec61.png) 大佬真没看到😂，是不是咱们权限不同哈

上面是我macOS逆向资源区看到的所有了

**Comment by QiuChenly** [comment]
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1737990&highlight=Hopper
Hopper Disassembler 5.7.7 完整版 

IDA只有7.0

**Comment by iRubbish** [comment]
感谢大佬分享
