### ISSUE TITLE
加载成功之后软件无法打开？

### ISSUE THREAD

**Issue by Frank-Fulank** [QiuChenly/MyMacsAppCrack#7]
按照步骤加载command成功之后，但是ishot打不开了，请问这是为啥？

**Comment by QiuChenly** [comment]
1. SIP关闭。
2. 确保文件没有被移动

**Comment by hoochanlon** [comment]
https://github.com/QiuChenly/MyMacsAppCrack/issues/8#issuecomment-1473101853
